version: "3.8"
services:
  backend:
    build: .
    ports:
      - "8080:8080"
  frontend:
    image: node:16
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]
